/* tslint:disable */
/* eslint-disable */
/**
 * VH Candidates service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Candidate
 */
export interface Candidate {
    /**
     * 
     * @type {string}
     * @memberof Candidate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Candidate
     */
    geo?: string;
    /**
     * 
     * @type {string}
     * @memberof Candidate
     */
    photo: string;
    /**
     * Skills of candidate
     * @type {Array<string>}
     * @memberof Candidate
     */
    skills: Array<string>;
}

export function CandidateFromJSON(json: any): Candidate {
    return CandidateFromJSONTyped(json, false);
}

export function CandidateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Candidate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'geo': !exists(json, 'geo') ? undefined : json['geo'],
        'photo': json['photo'],
        'skills': json['skills'],
    };
}

export function CandidateToJSON(value?: Candidate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'geo': value.geo,
        'photo': value.photo,
        'skills': value.skills,
    };
}


