/* tslint:disable */
/* eslint-disable */
/**
 * RT Orders service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    takeOffId?: number;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    orderType?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    time?: string;
    /**
     * queue | ready | taken
     * @type {string}
     * @memberof Order
     */
    status?: string;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'takeOffId': !exists(json, 'takeOffId') ? undefined : json['takeOffId'],
        'orderType': !exists(json, 'orderType') ? undefined : json['orderType'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function OrderToJSON(value?: Order | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'takeOffId': value.takeOffId,
        'orderType': value.orderType,
        'time': value.time,
        'status': value.status,
    };
}


