/* tslint:disable */
/* eslint-disable */
/**
 * RT Orders service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    Order,
    OrderFromJSON,
    OrderToJSON,
    OrderType,
    OrderTypeFromJSON,
    OrderTypeToJSON,
} from '../models';

export interface ListOrdersRequest {
    spotId?: string;
    startTime?: string;
    endTime?: string;
    page?: number;
}

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * List of orders
     */
    async listOrderTypesRaw(): Promise<runtime.ApiResponse<Array<OrderType>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/orders/types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderTypeFromJSON));
    }

    /**
     * List of orders
     */
    async listOrderTypes(): Promise<Array<OrderType>> {
        const response = await this.listOrderTypesRaw();
        return await response.value();
    }

    /**
     * List orders
     */
    async listOrdersRaw(requestParameters: ListOrdersRequest): Promise<runtime.ApiResponse<Array<Order>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.spotId !== undefined) {
            queryParameters['spotId'] = requestParameters.spotId;
        }

        if (requestParameters.startTime !== undefined) {
            queryParameters['startTime'] = requestParameters.startTime;
        }

        if (requestParameters.endTime !== undefined) {
            queryParameters['endTime'] = requestParameters.endTime;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/orders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrderFromJSON));
    }

    /**
     * List orders
     */
    async listOrders(requestParameters: ListOrdersRequest): Promise<Array<Order>> {
        const response = await this.listOrdersRaw(requestParameters);
        return await response.value();
    }

}
