swagger: "2.0"
info:
  version: "0.0.4"
  title: RT Orders service
# during dev, should point to your local machine
host: localhost:10011
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /orders:
    # binds a127 app logic to a route
    x-swagger-router-controller: orders
    get:
      description: List orders
      # used as the method name of the controller
      operationId: listOrders
      parameters:
        - name: spotId
          in: query
          description: Order to filter out
          required: false
          type: string
        - name: startTime
          in: query
          description: Start time of orders updates
          required: false
          type: string  
        - name: endTime
          in: query
          description: End time of orders updates
          required: false
          type: string   
        - name: page
          in: query
          description: Page to iterate, 1 is default
          required: false
          type: number             
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
                $ref: "#/definitions/Order"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"


  /orders/types:
    # binds a127 app logic to a route
    x-swagger-router-controller: orders
    get:
      description: List of orders
      # used as the method name of the controller
      operationId: listOrderTypes
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
                $ref: "#/definitions/OrderType"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
            
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Order:
    required:
      - id
    properties:
      id:
        type: string
      takeOffId:
        type: number
      orderType:
        type: string
      time:
        type: string
      status:
        description: queue | ready | taken
        type: string
       
       
  OrderType:
    required:
      - name
    properties:
      id:
        type: string
      name:
        type: string
        
        
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string