# http routing section
[http]
  [http.routers]
    # Define a connection between requests and services
    [http.routers.express]
      entryPoints = ["web"]
      rule = "PathPrefix(`/feedback`)"
      service = "express-feedback"

    [http.routers.swagger-orders]
      entryPoints = ["web"]
      rule = "PathPrefix(`/api/v1/tea`)"
      service = "swagger-orders"

  [http.services]
    # Define how to reach an existing service on our infrastructure
    [http.services.express-feedback.loadBalancer]
      [[http.services.express-feedback.loadBalancer.servers]]
        url = "http://127.0.0.1:3000/"

    [http.services.swagger-orders.loadBalancer]
      [[http.services.swagger-orders.loadBalancer.servers]]
        url = "http://127.0.0.1:10011/"